language: php
php:
    - 7.2.2

install:
    - composer install

stages:
    - Linting & Coding standards
    - Code analysis

jobs:
    include:
        - stage: Linting & Coding standards
          script: vendor/bin/parallel-lint --exclude vendor/ .
        - stage: Linting & Coding standards
          script: vendor/bin/phpcs --standard=PSR2 --extensions=php --ignore=vendor/ .
        - stage: Code analysis
          script: vendor/bin/phploc --count-tests --exclude vendor/ .
        - stage: Code analysis
          script: vendor/bin/phpcpd .
        - stage: unit tests
          addons:
            mariadb: '10.3'
          script:
            - git clone git://develop.git.wordpress.org/ build/wordpress-develop
            - mv build/wp-tests-config.php build/wordpress-develop/wp-tests-config.php
