language: php
php:
    - 7.2.2

install:
    - composer install

jobs:
    include:
        - stage: test
          script:
            - vendor/bin/parallel-lint --exclude vendor/ .
            - vendor/bin/phpcs --report=checkstyle --report-file=`pwd`/build/logs/checkstyle.xml --standard=PSR2 --extensions=php --ignore=vendor/ . || exit 0
            - vendor/bin/phploc --count-tests --exclude vendor/ --log-csv build/logs/phploc.csv --log-xml build/logs/phploc.xml .


stages:
    - test
