sudo: required

language: php
php:
    - 7.2.2

services:
    - docker

before_install:
    - docker pull php:7.2.2-cli-alpine3.7

install:
    - docker run php:7.2.2-cli-alpine3.7

jobs:
    include:
        - stage: prepare
          script: composer install
        - stage: lint
          script: vendor/bin/parallel-lint --exclude vendor/ .
        - stage: coding standards
          script: endor/bin/phpcs --report=checkstyle --report-file=`pwd`/build/logs/checkstyle.xml --standard=PSR2 --extensions=php --ignore=vendor/ . || exit 0
        - stage: code analyzation
          script: vendor/bin/phploc --count-tests --exclude vendor/ --log-csv build/logs/phploc.csv --log-xml build/logs/phploc.xml .

stages:
    - prepare
    - lint
    - coding standards
    - code analyzation
