language: php
php:
    - 7.1

install:
    - composer install

script:
    - vendor/bin/parallel-lint --exclude vendor/ .
    - vendor/bin/phpcs --standard=PSR2 --extensions=php  --ignore=plugins/ content
    - vendor/bin/phploc --count-tests --exclude=vendor/ --exclude=wp/ --exclude=content/plugins .
    - vendor/bin/phpcpd --exclude=vendor/ --exclude=wp/ --exclude=content/plugins/ .

before_deploy:
    - openssl aes-256-cbc -K $encrypted_ee097fe4a8ef_key -iv $encrypted_ee097fe4a8ef_iv -in .travis/deploy_new.enc -out /tmp/deploy_new -d
    - eval "$(ssh-agent -s)"
    - chmod 600 /tmp/deploy_new
    - ssh-add /tmp/deploy_new

deploy:
    skip_cleanup: true
    provider: script
    script:
        rm -r .git
        rm .gitignore
        rsync -av --delete ./ deploy@lotta.io:~/sites/develop/travis-test
    on:
        branch: develop
