language: php
php:
    - 7.2.2

install:
    - composer install

jobs:
    include:
        - stage: lint
          script: vendor/bin/parallel-lint --exclude vendor/ .
        - stage: coding standards
          script: vendor/bin/phpcs --report=checkstyle --report-file=`pwd`/build/logs/checkstyle.xml --standard=PSR2 --extensions=php --ignore=vendor/ . || exit 0
        - stage: analysis
          script: vendor/bin/phploc --count-tests --exclude vendor/ --log-csv build/logs/phploc.csv --log-xml build/logs/phploc.xml .
        - stage: wordpress theme unit tests
          addons:
            mariadb: '10.3'
          script: echo 'lol'

stages:
    - lint
    - coding standards
    - analysis
    - wordpress theme unit tests
