language: php
php:
    - 7.2.2

install:
    - composer install

stages:
    - test

jobs:
    include:
        - stage: test
          script: vendor/bin/parallel-lint --exclude vendor/ .
        - stage: test
          script: vendor/bin/phpcs --standard=PSR2 --extensions=php --ignore=vendor/ .
        - stage: test
          script: vendor/bin/phploc --count-tests --exclude vendor/ .
