sudo: required

services:
    - docker

language: php
php:
    - 7.2.2

before_install:
    - docker pull php:7.2.2-alpine3.7
    - docker run php:7.2.2-alpine3.7

install: composer install

jobs:
    include:
        - stage: lint
          script: vendor/bin/parallel-lint --exclude vendor/ .
        - stage: coding standards
          script: endor/bin/phpcs --report=checkstyle --report-file=`pwd`/build/logs/checkstyle.xml --standard=PSR2 --extensions=php --ignore=vendor/ . || exit 0
        - stage: analysis
          script: vendor/bin/phploc --count-tests --exclude vendor/ --log-csv build/logs/phploc.csv --log-xml build/logs/phploc.xml .

stages:
    - lint
    - coding standards
    - analysis
